### ISSUE TITLE
$.ajax can't POST uri encoded data

### ISSUE THREAD

**Issue by morungos** [chocolatechipui/ChocolateChipJS#23]
The code uses `encodeURIComponent` on the passed data as a single entity, whatever it is passed. This means that form data gets all the `=` and `&` characters encoded out. As far as I can tell, $.post isn't affected by this, but it's API isn't as powerful or flexible. 

In an ideal world, an object would be encoded properly, but I could live without any encoding. My 2 second reading of the jQuery docs are that a string passed to $.ajax is not encoded, only objects are. I can provide a PR if it'll help.

**Comment by chocolatechipui** [comment]
Sure, I'd like to see what your trying to do so I can set up a test case on my end to fix this.

**Comment by morungos** [comment]
The relevant fragment of code is (CS syntax) below. What actually gets posted is: `username%3Dtest%26password%3Dpass`. Basically, the `=` and `&` in my query string get put into `encodeURIComponent` again, and therefore never get sent to the server. In effect, `$.ajax` can't POST regular `application/x-www-form-urlencoded` form data. 

The jQuery docs for `$.ajax` describe the `data` parameter as: 

> Data to be sent to the server. It is converted to a query string, if not already a string.

So my reading is that if `data` is a string, it can be passed transparently. Being a subset, you don't need to support objects, but if you do, you can assemble a query string by `encodeURIComponent` on values alone. 

```
  queryString = "username=" + encodeURIComponent(username) + "&password=" + encodeURIComponent(password)

  $.ajax({
    url : "http://localhost:3001/api/data"
    type: "POST"
    headers: {
      "Content-Type" : "application/x-www-form-urlencoded"
    }
    data: queryString
    success: (data) ->
      console.log "Success", data
    error: (data) ->
      console.log "Error", data
  })
```

**Comment by morungos** [comment]
The short version is the following lines in `$.ajax` can be likely deleted and then it'll behave like a subset of jQuery:

```
      if (options.data) {
        options.data = encodeURIComponent(options.data);
      }
```

**Comment by morungos** [comment]
Oh weird. Now I see there are two different implementations in the src folder, in `ajax.js` and `xhr.js`. The `ajax.js` version doesn't do this, but the dist (which is using `xhr.js`, seemingly) does. There are bunch of other differences which I don't really want to go through now. 

This explains why `$.post` isn't available either. I've tried `$.ajax.post` which does exist, but doesn't seem to POST. 

It looks to me like the promises logic somehow broke `xhr.js`, so that basic GET requests using `$.ajax` are probably okay but everything else is out of whack. 

Hope that helps, as before, I can provide a PR if needed.

**Comment by chocolatechipui** [comment]
So, they're are slightly different versions depending on whether you build ChocolateChipJS with support for the older jQuery style Deferred object or the newer ECMAScript 6 Promises spec. By default it builds with support for Promises, which incorporates the xhr file. Otherwise, using the flag `gulp --deferredSupport true` it builds with jQuery-style Deferred object support that incorporates ajax.js. The main difference between these is that xhr returns Promises and expects Promise specific functionality. And the build with Deferred support implements Ajax with jQuery style deferred usage.

I hope that's clear. 

I'm setting up an Ajax test server so I can run a bunch of tests to sort this out so bear with me.

**Comment by chocolatechipui** [comment]
By the way, which version are you using?

**Comment by morungos** [comment]
I've been using the 8.9.10 tag, which seems the most recent available from bower, because 8.9.11 isn't tagged. It's the dist bundled code, which includes Promises. 

I'll switch to jQuery or raw XHR  for now so I can complete my development, and then maybe switch back. That'll get you off my critical path.

**Comment by chocolatechipui** [comment]
Thanks, I'm just winding down from a complete rewrite of it in TypeScript, which was a job, but caught lots of niggly things that even unit tests never caught. Looks like I need to add a serialize method to match what jQuery does.

**Comment by chocolatechipui** [comment]
Well, we decided to do something radical. We dumped the Ajax module totally and replaced it with the Fetch API from WHATWG. It's simpler and cleaner. There's a $.serialize method to properly serialize form content. And lots of examples of GET, POST, PUT and DELETE using PHP controllers. Look in the fetch folder. Of course, you need to run this in a PHP server instance. Also check out the updated docuemntation on the site under Fetch.

**Comment by morungos** [comment]
Great plan, sounds perfect.

**Comment by chocolatechipui** [comment]
Download latest and take a look. Seems to be working for my PHP tests. You can find out more about `fetch`: 
https://jakearchibald.com/2015/thats-so-fetch/
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
One thing, the spec is dependent on a number of streaming buffers being available. Unfortunately these are not available if your target is Android (Native Android Browser) or iOS.
I've deviated from the speck by adding in the ability to timeout a request. Not sure why they couldn't figure that out yet. If they come up if a means of canceling promise/requests, I'll look into updating our fetch API to match it.
